# Generated by Django 5.2.7 on 2025-10-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
                ('smoking_status', models.CharField(blank=True, max_length=50)),
                ('alcohol_consumption', models.CharField(blank=True, max_length=255)),
                ('dietary_habits', models.TextField(blank=True)),
                ('past_medical_conditions', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('present_symptoms', models.TextField(blank=True)),
                ('psychometric_summary', models.TextField(blank=True)),
                ('vata_score', models.IntegerField(blank=True, null=True)),
                ('pitta_score', models.IntegerField(blank=True, null=True)),
                ('kapha_score', models.IntegerField(blank=True, null=True)),
                ('tongue_image', models.ImageField(blank=True, upload_to='images/tongue/')),
                ('eye_image', models.ImageField(blank=True, upload_to='images/eyes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
