# Generated by Django 5.2.7 on 2025-10-03 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientprofile_practitionerprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practitionerprofile',
            name='degree_certificate',
        ),
        migrations.CreateModel(
            name='DegreeCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='practitioners/certificates/')),
                ('practitioner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degree_certificates', to='patients.practitionerprofile')),
            ],
        ),
    ]
